### ISSUE TITLE
Using unnamed state vector with ssa.exact causes stack imbalance

### ISSUE THREAD

**Issue by nicholasdavies** [plfjohnson/adaptivetau#1]
Hi there,

Thanks for providing this useful package!

If the `init.values` vector passed to `ssa.exact` isn't named, there is a stack imbalance (more values `UNPROTECT`ed than `PROTECT`ed).

As an illustration, this code (from the documentation for `ssa.exact`) works fine:

```R
library(adaptivetau)

## Lotka-Volterra example
lvrates <- function(x, params, t) {
  with(params, {
    return(c(preygrowth*x["prey"],      ## prey growth rate
             x["prey"]*x["pred"]*eat,   ## prey death / predator growth rate
             x["pred"]*preddeath))      ## predator death rate
  })
}
params=list(preygrowth=10, eat=0.01, preddeath=10);
r=ssa.exact(c(prey = 1000, pred = 500),
            matrix(c(1,0, -2,1, 0,-1), nrow=2), lvrates, params, tf=2)
```

But this code causes a stack imbalance:
```R
library(adaptivetau)

## Lotka-Volterra example
lvrates <- function(x, params, t) {
  with(params, {
    return(c(preygrowth*x[1],      ## prey growth rate
             x[1]*x[2]*eat,   ## prey death / predator growth rate
             x[2]*preddeath))      ## predator death rate
  })
}
params=list(preygrowth=10, eat=0.01, preddeath=10);
r=ssa.exact(c(1000, 500),
            matrix(c(1,0, -2,1, 0,-1), nrow=2), lvrates, params, tf=2)
```

I think this is probably down to line 100 of adaptivetau.cpp:

```C++
            PROTECT(m_VarNames);
```

If you look in the destructor for `CStochasticEqns` (from line 242) it seems that there is a check missing for whether m_VarNames is NULL or not.

I am running R version 4.4.1 (2024-06-14) on Mac OS X.

**Comment by plfjohnson** [comment]
Thanks for the careful tracking down of this bug!  Should be fixed now with commit https://github.com/plfjohnson/adaptivetau/commit/8f4768b8f2f9e0f4abf4cfbafc1fab14d26ba5df.  Will submit new version to CRAN shortly.

**Comment by nicholasdavies** [comment]
thanks!
